### ISSUE TITLE
Service Unavailable / Unknown Error

### ISSUE THREAD

**Issue by CloakedAlien** [awernick/google-assistant-node#6]
I seem to be getting this, it might be from a rookie mistake but I'm getting it "with another nodejs package" as well so I think it'a bigger issue. Other are having the same so shouldn't be an authentication issue on my behalf.

Ready
{ wrappers_: null,
  messageId_: undefined,
  arrayIndexOffset_: -1,
  array: [ 14, 'Service unavailable.', [] ],
  pivot_: 1.7976931348623157e+308,
  convertedFloatingPointFields_: {} }
Error ocurred. Exiting...
{ Error: Unknown Error.
    at ClientDuplexStream._emitStatusIfDone (/home/cloakedalien/gatest/node_modules/grpc/src/client.js:255:19)
    at ClientDuplexStream._receiveStatus (/home/cloakedalien/gatest/node_modules/grpc/src/client.js:233:8)
    at /home/cloakedalien/gatest/node_modules/grpc/src/client.js:757:12
  code: 2,
  metadata: Metadata { _internal_repr: { 'content-disposition': [Object] } } }
Error ocurred. Exiting...
{ Error: Unknown Error.
    at ClientDuplexStream._emitStatusIfDone (/home/cloakedalien/gatest/node_modules/grpc/src/client.js:255:19)
    at ClientDuplexStream._receiveStatus (/home/cloakedalien/gatest/node_modules/grpc/src/client.js:233:8)
    at /home/cloakedalien/gatest/node_modules/grpc/src/client.js:757:12
  code: 2,
  metadata: Metadata { _internal_repr: { 'content-disposition': [Object] } } }
Error ocurred. Exiting...

**Comment by awernick** [comment]
Yeah, this error is something very common in the Google Assistant gRPC API. 
The error also happens in some of Google's Raspberry Pi / Python demos. The way they work through it is by implementing a retry mechanism. If the error persists after 3 tries, the program raises the error, otherwise it continues processing the data.

I will attempt to integrate this mechanism somehow into the package, but you can also try to implement it yourself within your project :)

**Comment by ItsWendell** [comment]
@awernick I'm getting the same issue using Electron and your node package. I got the authentication working using a Google OAuth2 node extension made for electron and I am generating a valid OAuth2 object to pass to your library.

The event 'ready' gets triggered, and that's when I input a microphone stream converted to an uint8array, (since I got an error that google couldn't convert the original data to a uint8array)

After 5 - 10 seconds of sending microphone information I get an 'Service Unavailable' error, no other events get triggered.

Could this be because I am using electron / localhost client to connect to Google?

**Comment by awernick** [comment]
@WMisiedjan Like I commented above, this is a general issue that happens in the gRPC API of the Google Assistant. Your best bet is to implement a retry mechanism for these types of requests. 

As you can see [here](https://github.com/googlesamples/assistant-sdk-python/blob/c9235021cdc114ef3b76e311fbcca48e086a7213/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py#L89), Google also has these types of errors, and the only way to get rid of them is by retrying the request.

**Comment by ItsWendell** [comment]
Hmh I see that Google sometimes has this issue, I got around it to initially call converse twice and retry if I get service unavailable errors, I now get and 'mic-mode' 'state' and 'end' event triggered, understanding that 'mic-mode' decides weather I not I should continue streaming the microphone data.

Other events don't get triggered for some reason, and tips / advice on how to debug this?
